version: '3.7'

services:
  app-web:
    container_name: app-web
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/usr/src/app/staticfiles/
      - media_volume:/usr/src/app/mediafiles/
    expose:
      - 8000
    env_file:
      - ./.env/production.env
    depends_on:
      - app-db
  app-db:
    container_name: app-db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env/production.env
  app-nginx:
    container_name: app-nginx
    image: nginx:1.19.0
    volumes:
      - static_volume:/var/www/staticfiles
      - media_volume:/var/www/mediafiles
      - ./nginx:/etc/nginx/templates
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app-web

volumes:
  postgres_data:
  static_volume:
  media_volume:
