version: '3.7'

services:
  app-web:
    env_file:
      - .env/production.env
    container_name: rattletat-web
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 config.wsgi:application
    volumes:
        - ${MOUNTPOINT_STATICFILES}:/home/app/staticfiles:rw
        - ${MOUNTPOINT_MEDIAFILES}:/home/app/mediafiles:rw
    expose:
      - 8000
    depends_on:
      - app-db
  app-db:
    container_name: rattletat-db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
