version: '3.7'

services:
  app-web:
    container_name: app-web
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env/production.env
    depends_on:
      - app-db
  app-db:
    container_name: app-db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env/production.env
  app-nginx:
    container_name: app-nginx
    image: nginx:1.19.0
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - nginx_conf:/etc/nginx/conf.d:ro
    ports:
      - 80:8000
      - 443:443
    depends_on:
      - app-web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  nginx_conf:
    driver_opts:
      type: none
      device: ./nginx
      o: bind
