version: '3.7'

services:
  app-web:
    container_name: rattletat-web
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 config.wsgi:application
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env/production.env
    depends_on:
      - app-db
  app-db:
    container_name: rattletat-db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env/production.env

volumes:
  postgres_data:
  static_volume:
  media_volume:
