# Generated by Django 3.1.5 on 2021-03-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='position',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
