# Generated by Django 3.1.7 on 2022-10-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210305_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='position',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
