# Generated by Django 3.1.14 on 2022-10-28 15:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20221021_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='tst', editable=False, max_length=500, populate_from='title'),
            preserve_default=False,
        ),
    ]
