# Generated by Django 3.1.7 on 2021-03-05 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210305_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomponent',
            old_name='css_identifier',
            new_name='identifier',
        ),
        migrations.RemoveField(
            model_name='postcomponent',
            name='css_classes',
        ),
    ]
