# Generated by Django 3.1.7 on 2021-03-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210305_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomponent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
