# Generated by Django 3.1.7 on 2021-03-05 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postcomponent_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomponent',
            name='title',
        ),
    ]
