# Generated by Django 3.1.14 on 2022-10-22 11:38

import apps.blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0014_auto_20221021_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComponent',
            fields=[
                ('postcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.postcomponent')),
                ('image', models.ImageField(upload_to=apps.blog.models.ImageComponent._image_path)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('blog.postcomponent',),
        ),
        migrations.CreateModel(
            name='PlotComponent',
            fields=[
                ('postcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.postcomponent')),
                ('javascript', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('blog.postcomponent',),
        ),
        migrations.AlterModelOptions(
            name='postcomponent',
            options={'ordering': ['post']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='javascript',
        ),
        migrations.RemoveField(
            model_name='postcomponent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='postcomponent',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='postcomponent',
            name='position',
        ),
        migrations.AddField(
            model_name='postcomponent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_blog.postcomponent_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='postcomponent',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.CreateModel(
            name='TextComponent',
            fields=[
                ('postcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.postcomponent')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('blog.postcomponent',),
        ),
    ]
