# Generated by Django 3.1.14 on 2022-10-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20221022_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomponent',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='postcomponent',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
