# Generated by Django 3.1.14 on 2023-07-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20221022_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fediverse_post',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
