# Generated by Django 3.0.6 on 2020-07-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='projects.Project'),
        ),
    ]
